### ISSUE TITLE
level-editor.json

### ISSUE THREAD

**Issue by partounian** [chrisdugne/cherry#2]
I noticed the level-editor.json is not included in this repo, is there any reason for that?

**Comment by chrisdugne** [comment]
`level-editor.json` is just a tmp file generated by your [LevelEditor](https://github.com/chrisdugne/cherry-editor)

the final `.json` should then be renamed and placed within your levels, for example https://github.com/chrisdugne/cherry/blob/master/assets/levels/chapter0/level1.json

thank you for trying `Cherry` @partounian :heart_eyes:
